platform:ios, '8.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 3.8.1'
pod 'ShareSDK3', '~> 3.3.2'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'AMapLocation', '~> 2.1.0'
pod 'Masonry', '~> 1.0.1'
